#include "stdlib_runtime.h"
#define RXF_FUNCTION __attribute__((noinline))
static __attribute__((always_inline)) inline rxf_object_entry *entry(rxf_runtime_context*c,rxf_u64 id){rxf_object_entry*e=(rxf_object_entry*)(unsigned long long)c->objects;for(rxf_u64 i=0;i<c->object_count;i++)if(e[i].id==id)return&e[i];return 0;}
static __attribute__((always_inline)) inline rxf_u32 valid(rxf_runtime_context*c){return c&&c->version==RXF_RUNTIME_ABI_VERSION&&c->size>=sizeof(*c);}
static __attribute__((always_inline)) inline rxf_transaction_member *members(rxf_runtime_context*c){return (rxf_transaction_member*)(unsigned long long)c->journal;}
static __attribute__((always_inline)) inline rxf_u32 member_index(rxf_runtime_context*c,rxf_transaction*t,rxf_u64 id,rxf_u64*out){if(!t||!t->active)return RXF_REFUSE_UNBOUND;rxf_transaction_member*m=members(c);for(rxf_u64 i=0;i<c->journal_capacity;i++)if(m[i].identity==t->identity&&m[i].object_id==id){*out=i;return RXF_OK;}return RXF_REFUSE_UNBOUND;}
static __attribute__((always_inline)) inline rxf_u32 access_typed(rxf_runtime_context*c,rxf_object_handle h,rxf_transaction*t,rxf_u64 expected,rxf_object_entry**out){if(!valid(c))return RXF_REFUSE_UNBOUND;rxf_object_entry*e=entry(c,h.object_id);if(!e)return RXF_REFUSE_UNBOUND;if(e->generation!=h.generation)return RXF_REFUSE_STALE_GENERATION;if(expected&&e->type_id!=expected)return RXF_REFUSE_TYPE_MISMATCH;if(e->state==RXF_OBJECT_PENDING){rxf_u64 i;if(!t||e->owner_transaction!=t->identity||member_index(c,t,e->id,&i))return RXF_REFUSE_UNBOUND;}else if(e->state!=RXF_OBJECT_LIVE)return RXF_REFUSE_UNBOUND;*out=e;return RXF_OK;}
static __attribute__((always_inline)) inline rxf_u32 access(rxf_runtime_context*c,rxf_object_handle h,rxf_transaction*t,rxf_object_entry**out){return access_typed(c,h,t,0,out);}
static __attribute__((always_inline)) inline rxf_u32 add_member(rxf_runtime_context*c,rxf_transaction*t,rxf_object_entry*e){if(!c->journal||c->journal_count>=c->journal_capacity)return RXF_REFUSE_JOURNAL_FULL;rxf_transaction_member*m=members(c);rxf_u64 slot=c->journal_capacity;for(rxf_u64 i=0;i<c->journal_capacity;i++)if(!m[i].identity){slot=i;break;}if(slot==c->journal_capacity)return RXF_REFUSE_JOURNAL_FULL;m+=slot;m->identity=t->identity;m->object_id=e->id;m->old_generation=e->generation;m->old_type_id=e->type_id;m->old_payload=e->payload;m->old_size=e->size;m->old_capacity=e->capacity;m->old_state=e->state;m->old_owner_transaction=e->owner_transaction;t->member_count++;c->journal_count++;return RXF_OK;}



RXF_FUNCTION rxf_u32 rxf_hash_u64(rxf_u64 key,rxf_u64 seed,rxf_u64*out){rxf_u64 h=seed;for(rxf_u32 i=0;i<8;i++){h^=(rxf_u8)(key>>(i*8));h*=1099511628211ULL;}*out=h;return RXF_OK;}
static __attribute__((always_inline)) inline rxf_u32 hash_header(rxf_runtime_context*c,rxf_object_handle h,rxf_transaction*t,rxf_u64 type,rxf_u64 bucket_type,rxf_u64 bucket_size,rxf_hash_header**header,rxf_object_entry**storage){rxf_object_entry*collection;rxf_u32 s=access_typed(c,h,t,type,&collection);if(s)return s;if(h.offset>collection->size||sizeof(rxf_hash_header)>collection->size-h.offset)return RXF_REFUSE_OUT_OF_RANGE;rxf_hash_header*x=(rxf_hash_header*)(unsigned long long)(collection->payload+h.offset);if(x->capacity<8||(x->capacity&(x->capacity-1))||x->count>x->capacity||x->tombstone_count>x->capacity-x->count)return RXF_REFUSE_OUT_OF_RANGE;if(x->capacity>((~(rxf_u64)0)/bucket_size))return RXF_REFUSE_OVERFLOW;rxf_object_entry*b;s=access_typed(c,x->bucket_storage,t,bucket_type,&b);if(s)return s;rxf_u64 span=x->capacity*bucket_size;if(x->bucket_storage.offset>b->size||span>b->size-x->bucket_storage.offset)return RXF_REFUSE_OUT_OF_RANGE;*header=x;*storage=b;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_hash_map_lookup(rxf_runtime_context*c,rxf_object_handle collection,rxf_transaction*t,rxf_u64 hash,rxf_u64 key,rxf_option_ref*out){volatile rxf_u64 zero=0;rxf_hash_header*h;rxf_object_entry*storage;rxf_u32 s=hash_header(c,collection,t,60017ULL,41018ULL,48,&h,&storage);if(s)return s;rxf_u64 base=storage->payload+h->bucket_storage.offset;for(rxf_u64 probe=0;probe<h->capacity;probe++){rxf_hash_map_bucket*b=(rxf_hash_map_bucket*)(unsigned long long)(base+(((hash+probe)&(h->capacity-1))*48));if(b->state==0){out->tag=(rxf_u32)zero;out->padding=(rxf_u32)zero;out->value.object_id=zero;out->value.generation=zero;out->value.offset=zero;return RXF_OK;}if(b->state>2)return RXF_REFUSE_OUT_OF_RANGE;if(b->state==1&&b->stored_hash==hash&&b->key==key){out->tag=1;out->padding=(rxf_u32)zero;out->value=b->value;return RXF_OK;}}out->tag=(rxf_u32)zero;out->padding=(rxf_u32)zero;out->value.object_id=zero;out->value.generation=zero;out->value.offset=zero;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_hash_set_lookup(rxf_runtime_context*c,rxf_object_handle collection,rxf_transaction*t,rxf_u64 hash,rxf_u64 key,rxf_option_u64*out){volatile rxf_u64 zero=0;rxf_hash_header*h;rxf_object_entry*storage;rxf_u32 s=hash_header(c,collection,t,60018ULL,41019ULL,24,&h,&storage);if(s)return s;rxf_u64 base=storage->payload+h->bucket_storage.offset;for(rxf_u64 probe=0;probe<h->capacity;probe++){rxf_hash_set_bucket*b=(rxf_hash_set_bucket*)(unsigned long long)(base+(((hash+probe)&(h->capacity-1))*24));if(b->state==0){out->tag=(rxf_u32)zero;out->padding=(rxf_u32)zero;out->value=zero;return RXF_OK;}if(b->state>2)return RXF_REFUSE_OUT_OF_RANGE;if(b->state==1&&b->stored_hash==hash&&b->key==key){out->tag=1;out->padding=(rxf_u32)zero;out->value=b->key;return RXF_OK;}}out->tag=(rxf_u32)zero;out->padding=(rxf_u32)zero;out->value=zero;return RXF_OK;}

RXF_FUNCTION rxf_u32 rxf_runtime_begin_private(rxf_runtime_context*c,rxf_object_handle object,rxf_u64 identity,rxf_transaction*out){if(!valid(c)||!out||!object.object_id||!identity||out->active||!c->journal_capacity||!c->journal)return RXF_REFUSE_OUT_OF_RANGE; volatile rxf_u64 zero=0;out->root_object_id=object.object_id;out->old_frontier=c->heap_frontier;out->identity=identity;out->member_count=zero;out->active=1;out->reserved=zero;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_resolve(rxf_runtime_context*c,rxf_object_handle h,rxf_u64 n,rxf_u64*out){rxf_object_entry*e;rxf_u32 s=access(c,h,0,&e);if(s)return s;if(h.offset>e->size||n>e->size-h.offset)return RXF_REFUSE_OUT_OF_RANGE;*out=e->payload+h.offset;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_resolve_typed(rxf_runtime_context*c,rxf_object_handle h,rxf_transaction*t,rxf_u64 expected,rxf_u64 n,rxf_u64*out){rxf_object_entry*e;rxf_u32 s=access_typed(c,h,t,expected,&e);if(s)return s;if(h.offset>e->size||n>e->size-h.offset)return RXF_REFUSE_OUT_OF_RANGE;*out=e->payload+h.offset;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_allocate_prepare(rxf_runtime_context*c,rxf_u64 id,rxf_u64 type_id,rxf_u64 initial_size,rxf_u64 capacity,rxf_u64 a,rxf_transaction*t,rxf_object_handle*out){if(!valid(c)||!t||!t->active||!type_id||initial_size>capacity||!a||(a&(a-1)))return RXF_REFUSE_OUT_OF_RANGE; volatile rxf_u64 zero=0;rxf_u64 p=(c->heap_frontier+a-1)&~(a-1);if(p<c->heap_frontier||p>c->heap_limit||capacity>c->heap_limit-p)return RXF_REFUSE_OUT_OF_MEMORY;rxf_object_entry*e=entry(c,id);if(!e||e->state)return RXF_REFUSE_UNBOUND;rxf_u32 s=add_member(c,t,e);if(s)return s;e->generation++;e->type_id=type_id;e->payload=c->heap_base+p;e->size=initial_size;e->capacity=capacity;e->state=RXF_OBJECT_PENDING;e->read_borrows=zero;e->pin_count=zero;e->owner_transaction=t->identity;c->heap_frontier=p+capacity;out->object_id=id;out->generation=e->generation;out->offset=0;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_publish(rxf_runtime_context*c,rxf_transaction*t){if(!valid(c)||!t||!t->active||!t->member_count)return RXF_REFUSE_UNBOUND;rxf_transaction_member*m=members(c);rxf_u64 found=0;for(rxf_u64 i=0;i<c->journal_capacity;i++)if(m[i].identity==t->identity){rxf_object_entry*e=entry(c,m[i].object_id);if(!e||e->state!=RXF_OBJECT_PENDING||e->owner_transaction!=t->identity)return RXF_REFUSE_UNBOUND;found++;}if(found!=t->member_count)return RXF_REFUSE_UNBOUND;for(rxf_u64 i=0;i<c->journal_capacity;i++)if(m[i].identity==t->identity){rxf_object_entry*e=entry(c,m[i].object_id);e->state=RXF_OBJECT_LIVE;e->owner_transaction=0;m[i].identity=0;c->journal_count--;}t->active=0;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_rollback(rxf_runtime_context*c,rxf_transaction*t){if(!valid(c)||!t||!t->active||!t->member_count)return RXF_REFUSE_UNBOUND;rxf_transaction_member*m=members(c);rxf_u64 found=0;for(rxf_u64 i=0;i<c->journal_capacity;i++)if(m[i].identity==t->identity){rxf_object_entry*e=entry(c,m[i].object_id);if(!e||e->state!=RXF_OBJECT_PENDING||e->owner_transaction!=t->identity)return RXF_REFUSE_UNBOUND;found++;}if(found!=t->member_count)return RXF_REFUSE_UNBOUND;for(rxf_u64 i=c->journal_capacity;i;i--)if(m[i-1].identity==t->identity){rxf_object_entry*e=entry(c,m[i-1].object_id);e->generation=m[i-1].old_generation;e->type_id=m[i-1].old_type_id;e->payload=m[i-1].old_payload;e->size=m[i-1].old_size;e->capacity=m[i-1].old_capacity;e->state=m[i-1].old_state;e->owner_transaction=m[i-1].old_owner_transaction;m[i-1].identity=0;c->journal_count--;}c->heap_frontier=t->old_frontier;t->active=0;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_release(rxf_runtime_context*c,rxf_object_handle h){rxf_object_entry*e;rxf_u32 s=access(c,h,0,&e);if(s)return s;if(e->read_borrows)return RXF_REFUSE_BORROW_CONFLICT;if(e->pin_count)return RXF_REFUSE_PINNED;e->state=0;e->payload=0;e->size=0;e->capacity=0;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_borrow(rxf_runtime_context*c,rxf_object_handle h,rxf_u64 mut){rxf_object_entry*e;rxf_u32 s=access(c,h,0,&e);if(s)return s;if((mut&&e->read_borrows)||(!mut&&(e->read_borrows&RXF_BORROW_MUTABLE)))return RXF_REFUSE_BORROW_CONFLICT;e->read_borrows=mut?RXF_BORROW_MUTABLE:e->read_borrows+1;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_release_borrow(rxf_runtime_context*c,rxf_object_handle h,rxf_u64 mut){rxf_object_entry*e;rxf_u32 s=access(c,h,0,&e);if(s)return s;if(mut){if(e->read_borrows!=RXF_BORROW_MUTABLE)return RXF_REFUSE_BORROW_CONFLICT;e->read_borrows=0;}else{if(!e->read_borrows||(e->read_borrows&RXF_BORROW_MUTABLE))return RXF_REFUSE_BORROW_CONFLICT;e->read_borrows--;}return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_pin(rxf_runtime_context*c,rxf_object_handle h){rxf_object_entry*e;rxf_u32 s=access(c,h,0,&e);if(s)return s;e->pin_count++;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_unpin(rxf_runtime_context*c,rxf_object_handle h){rxf_object_entry*e;rxf_u32 s=access(c,h,0,&e);if(s)return s;if(!e->pin_count)return RXF_REFUSE_PINNED;e->pin_count--;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_read(rxf_runtime_context*c,rxf_object_handle h,rxf_transaction*t,rxf_u64 off,rxf_u64 n,rxf_u64*out){rxf_object_entry*e;rxf_u32 s=access(c,h,t,&e);if(s)return s;if(h.offset>e->size||off>e->size-h.offset||n>e->size-h.offset-off)return RXF_REFUSE_OUT_OF_RANGE;*out=e->payload+h.offset+off;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_write(rxf_runtime_context*c,rxf_object_handle h,rxf_transaction*t,rxf_u64 off,rxf_u64 src,rxf_u64 n){rxf_object_entry*e;rxf_u32 s=access(c,h,t,&e);if(s)return s;if(h.offset>e->capacity||off>e->capacity-h.offset||n>e->capacity-h.offset-off)return RXF_REFUSE_OUT_OF_RANGE;rxf_u64 p=e->payload+h.offset+off;for(rxf_u64 i=0;i<n;i++)((rxf_u8*)(unsigned long long)p)[i]=((rxf_u8*)(unsigned long long)src)[i];if(off+n>e->size)e->size=off+n;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_reserve(rxf_runtime_context*c,rxf_object_handle h,rxf_transaction*t,rxf_u64 n){rxf_object_entry*e;rxf_u32 s=access(c,h,t,&e);if(s)return s;return n<=e->capacity?RXF_OK:RXF_REFUSE_OUT_OF_MEMORY;}
RXF_FUNCTION rxf_u32 rxf_runtime_append(rxf_runtime_context*c,rxf_object_handle h,rxf_transaction*t,rxf_u64 src,rxf_u64 n){rxf_object_entry*e;rxf_u32 s=access(c,h,t,&e);if(s)return s;if(n>e->capacity-e->size)return RXF_REFUSE_OUT_OF_MEMORY;for(rxf_u64 i=0;i<n;i++)((rxf_u8*)(unsigned long long)e->payload)[e->size+i]=((rxf_u8*)(unsigned long long)src)[i];e->size+=n;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_format_u32(rxf_runtime_context*c,rxf_object_handle h,rxf_transaction*t,rxf_u32 v){rxf_object_entry*e;rxf_u32 s=access(c,h,t,&e);if(s)return s;rxf_u8 tmp[10];rxf_u64 n=0;do{tmp[n++]=(rxf_u8)('0'+v%10);v/=10;}while(v);if(n>e->capacity-e->size)return RXF_REFUSE_OUT_OF_RANGE;for(rxf_u64 i=0;i<n;i++)((rxf_u8*)(unsigned long long)e->payload)[e->size+i]=tmp[n-1-i];e->size+=n;return RXF_OK;}
RXF_FUNCTION rxf_u32 rxf_runtime_search(rxf_runtime_context*c,rxf_object_handle hay_handle,rxf_u64 hn,rxf_object_handle needle_handle,rxf_u64 nn,rxf_transaction*t,rxf_u64*out){rxf_object_entry*hay_entry;rxf_u32 s=access(c,hay_handle,t,&hay_entry);if(s)return s;rxf_object_entry*needle_entry;s=access(c,needle_handle,0,&needle_entry);if(s)return s;if(hay_handle.offset>hay_entry->size||hn>hay_entry->size-hay_handle.offset||needle_handle.offset>needle_entry->size||nn>needle_entry->size-needle_handle.offset)return RXF_REFUSE_OUT_OF_RANGE;rxf_u64 hay=hay_entry->payload+hay_handle.offset;rxf_u64 needle=needle_entry->payload+needle_handle.offset;if(!nn){*out=0;return RXF_OK;}for(rxf_u64 i=0;i+nn<=hn;i++){rxf_u64 j=0;while(j<nn&&((rxf_u8*)(unsigned long long)hay)[i+j]==((rxf_u8*)(unsigned long long)needle)[j])j++;if(j==nn){*out=i;return RXF_OK;}}return RXF_REFUSE_OUT_OF_RANGE;}
RXF_FUNCTION rxf_u32 rxf_runtime_cleanup(rxf_runtime_context*c,rxf_transaction*t){if(!t||!t->active)return RXF_OK;if(!valid(c)||!t->member_count)return RXF_REFUSE_UNBOUND;rxf_transaction_member*m=members(c);rxf_u64 found=0;for(rxf_u64 i=0;i<c->journal_capacity;i++)if(m[i].identity==t->identity){rxf_object_entry*e=entry(c,m[i].object_id);if(!e||e->state!=RXF_OBJECT_PENDING||e->owner_transaction!=t->identity)return RXF_REFUSE_UNBOUND;found++;}if(found!=t->member_count)return RXF_REFUSE_UNBOUND;for(rxf_u64 i=c->journal_capacity;i;i--)if(m[i-1].identity==t->identity){rxf_object_entry*e=entry(c,m[i-1].object_id);e->generation=m[i-1].old_generation;e->type_id=m[i-1].old_type_id;e->payload=m[i-1].old_payload;e->size=m[i-1].old_size;e->capacity=m[i-1].old_capacity;e->state=m[i-1].old_state;e->owner_transaction=m[i-1].old_owner_transaction;m[i-1].identity=0;c->journal_count--;}c->heap_frontier=t->old_frontier;t->active=0;return RXF_OK;}
