"""Public executable packaging model API."""

from pymergetic.rxf.executable.bios import (
    BiosImageError,
    BiosManifest,
    BiosSegment,
    build_bios_image,
    parse_bios_image,
)
from pymergetic.rxf.executable.models import (
    ArtifactFormat,
    DiagnosticSeverity,
    ExecutableDiagnostic,
    ExecutableImage,
    ExecutablePlatform,
    ExecutableProvenance,
    ExecutableSegment,
    ExecutableSymbol,
    ExecutableTarget,
    RuntimeTable,
    RuntimeTableKind,
    SegmentKind,
    SegmentPermissions,
    SymbolKind,
)
from pymergetic.rxf.executable.pipeline import (
    CAPABILITY_ENTRY_SIZE,
    FUNCTION_ENTRY_SIZE,
    OBJECT_ENTRY_SIZE,
    RUNTIME_CONTEXT_SIZE,
    TRANSACTION_ENTRY_SIZE,
    ExecutableBuildError,
    ExecutableLayout,
    ExecutablePlan,
    PlannedFunction,
    build_executable_image,
    build_image,
    plan_executable,
)
from pymergetic.rxf.executable.targets import (
    EXECUTABLE_TARGETS,
    resolve_executable_target,
)

__all__ = [
    "CAPABILITY_ENTRY_SIZE",
    "EXECUTABLE_TARGETS",
    "FUNCTION_ENTRY_SIZE",
    "OBJECT_ENTRY_SIZE",
    "RUNTIME_CONTEXT_SIZE",
    "TRANSACTION_ENTRY_SIZE",
    "ArtifactFormat",
    "BiosImageError",
    "BiosManifest",
    "BiosSegment",
    "DiagnosticSeverity",
    "ExecutableBuildError",
    "ExecutableDiagnostic",
    "ExecutableImage",
    "ExecutableLayout",
    "ExecutablePlan",
    "ExecutablePlatform",
    "ExecutableProvenance",
    "ExecutableSegment",
    "ExecutableSymbol",
    "ExecutableTarget",
    "PlannedFunction",
    "RuntimeTable",
    "RuntimeTableKind",
    "SegmentKind",
    "SegmentPermissions",
    "SymbolKind",
    "build_bios_image",
    "build_executable_image",
    "build_image",
    "parse_bios_image",
    "plan_executable",
    "resolve_executable_target",
]
